export const initialFormState = {
  dcodE1: "",
  dcodE2: "",
  dname: "",
  dnamE2: "",
  num: 0,
  doldacC1: 0,
  doldacC2: 0,
  doldacc: 0,
  dcurrenT1: 0,
  dcurrenT2: 0,
  dcacc: 0,
  ddacc: 0,
  dcaccm: 0,
  ddaccm: 0,
  ddeP_AMOUNT: 0,
  ddeP_PER: 0,
  dacC_TYPE0: "",
  dacC_TYPE: "",
  dacC_TYPE2: "",
  ddeP_CODE: "",
  dfdate: null,
  dtdate: null,
  dacC_TNAME: "",
  daddress: "",
  daddresS2: "",
  dcrediT_LIMT: 0,
  dpurchase: 0,
  dpurchasedate: null,
  ddeP_NAME: "",
  dphone: "",
  dphonE2: "",
  dvaluedate: null,
  dvalue: 0,
  dcurrency: "",
  dtelx: "",
  dpager: "",
  ddate: null,
  dlevel: 0,
  dsecondry: false,
  remark: "",
  doldacccurr: 0,
  ddacccurr: 0,
  dcacccurr: 0,
  accumulatecode: "",
  och_rate: 0,
  scur: 0,
  dstop: false,
  email: "",
  mor1: "",
  mor2: "",
  mor3: "",
  mor4: "",
  mor5: "",
  acc_Rem: "",
  accshow_Rem: false,
  dStop_Rem: "",
  u_date_a: null,
  u_time_a: null,
  dperiod_allow: 0,
  acC_TYPE: 0,
  dtelother: "",
  demployee: "",
  dslaes: "",
  emaiL_MSG: false,
  costCRelate: false,
  fixExclusion: false,
  fixExclDate: null,
  accVatNo: "",
  monDedction: 0,
  iqamaNo: "",
  iqamaExp: null,
  monDedStart: null,
  nextDedDate: null,
  dedInterval: 0,
  dbAccBfPr: 0,
  dcAccBfPr: 0,
  dOldAcc1Pr: 0,
  dOldAcc2Pr: 0,
  dOldAccPr: 0,
  dbAccDurPr: 0,
  dcAccDurPr: 0,
  currDbBlnc: 0,
  currCrBlnc: 0,
  currNetBlnc: 0,
  depAmount: 0,
  accumulateBalance: 0,
  accumulateName: "",
  dadd: 0,
  dadD_Dep: 0,
  dailyDep: 0,
  ddeP_years: 0,
  depbal: 0,
  depByTime: 0,
  depDayes: 0,
  dold: 0,
  dRem: 0,
  dRem_Dep: 0,
  endDate: null,
  finalBAL: 0,
  absCurrBlnce: 0,
  baL1: 0,
  baL2: 0,
  currNetBalance: 0,
  disp: "",
  ilCase: "",
  rColor: 0,
  stB_BACK: "",
  oriFTYPE: "",
  ftype: "",
  docTypeName: "",
  codE2: "",
  gRegNo: 0,
  onumber: 0,
  bookno: "",
  fdate: null,
  fcode: "",
  tcode: "",
  fname: "",
  tname: "",
  amount: 0,
  paid: 0,
  bamount: 0,
  change: 0,
  totdiscount: 0,
  cost: 0,
  paide: 0,
  posted: 0,
  cH_RATE: 0,
  dutY_DAY: 0,
  useR_NO: 0,
  username: "",
  seller: "",
  sellername: "",
  ref: "",
  chK_NO: "",
  chK_DATE: null,
  banK_NAME: "",
  name: "",
  cost_Center: "",
  jobNo: 0,
  orderNo: 0,
  dlvType: 0,
  paymode: "",
  paymodeno: "",
  taxcost: 0,
  shipcost: 0,
  othercost: 0,
  custAddr: "",
  custTel: "",
  custFax: "",
  invoice_Date: null,
  u_DATE_E: null,
  estUserNo: "",
  estUserName: "",
  u_TIME_E: null,
  invoicE_NO: "",
  ncust: "",
  codE3: "",
  nameref1: "",
  cash_no: "",
  unitf: 0,
  shifT_NO: "",
  nameref2: "",
  brnno: "",
  wsname: "",
  wsno: "",
  bwo: 0,
  amount2: 0,
  ch_rate2: 0,
  fileno: 0,
  cmpacc: 0,
  pantname: "",
  remark1: "",
  remark2: "",
  diq: "",
  phrdis: 0,
  inuacc: "",
  amount3: 0,
  currName: "",
  fixExcName: "",
  landNo: "",
  landName: "",
  restAccName: "",
  restAccNo: "",
  vouArrangeNo: "",
  vouDiscType: 0,
  vouDiscPer: 0,
  vouDiscAmount: 0,
  vouTotDisc: 0,
  itmTotDisc: 0,
  itmTotQnt: 0,
  invCost: 0,
  totAmntWithoutDisc: 0,
  totAmntBfDisc: 0,
  totAmntAfItmDisc: 0,
  vatAmnt: 0,
  totAmntAfVat: 0,
  selleR2: "",
  sellernamE2: "",
  cust2Accno: "",
  cust2Name: "",
  cust2Mobile: "",
  cust2Address: "",
  invCode2: "",
  gNot01: "",
  gNot02: "",
  gNot03: "",
  gNot04: "",
  gNot05: "",
  gNot06: "",
  gNot07: "",
  gNot08: "",
  gNot09: "",
  gNot10: "",
  gNot11: "",
  gNot12: "",
  gNot13: "",
  gNot14: "",
  gNot15: "",
  maturityStart: null,
  maturityEnd: null,
  rowBColor: 0,
  acc_arrang: 0,
  accGranted: false,
  dNum: 0,
  crNo: "",
  cntryName: "",
  cntryIdCode: "",
  cntrySubentity: "",
  postalCode: "",
  cityName: "",
  citySubDivsion: "",
  plotId: "",
  buildNo: "",
  streetname: "",
  addStreetname: "",
  g_Date01: null,
  g_Date02: null,
  ctActive: 0,
  curUntStr: "",
  curUntNo: 0,
  curAkrName: "",
  curAkrNo: "",
};
const toDate = (val) => {
  if (!val) return null;
  try {
    return new Date(val).toISOString();
  } catch {
    return null;
  }
};

export const processFormData = (formState) => ({
  dcodE1: formState.dcodE1 ?? "",
  dcodE2: formState.dcodE2 ?? "",
  dname: formState.dname ?? "",
  dnamE2: formState.dnamE2 ?? "",
  num: formState.num ?? 0,
  doldacC1: formState.doldacC1 ?? 0,
  doldacC2: formState.doldacC2 ?? 0,
  doldacc: formState.doldacc ?? 0,
  dcurrenT1: formState.dcurrenT1 ?? 0,
  dcurrenT2: formState.dcurrenT2 ?? 0,
  dcacc: formState.dcacc ?? 0,
  ddacc: formState.ddacc ?? 0,
  dcaccm: formState.dcaccm ?? 0,
  ddaccm: formState.ddaccm ?? 0,
  ddeP_AMOUNT: formState.ddeP_AMOUNT ?? 0,
  ddeP_PER: formState.ddeP_PER ?? 0,
  dacC_TYPE0: formState.dacC_TYPE0 ?? "",
  dacC_TYPE: formState.dacC_TYPE ?? "",
  dacC_TYPE2: formState.dacC_TYPE2 ?? "",
  ddeP_CODE: formState.ddeP_CODE ?? "",
  dfdate: toDate(formState.dfdate),
  dtdate: toDate(formState.dtdate),
  dacC_TNAME: formState.dacC_TNAME ?? "",
  daddress: formState.daddress ?? "",
  daddresS2: formState.daddresS2 ?? "",
  dcrediT_LIMT: formState.dcrediT_LIMT ?? 0,
  dpurchase: formState.dpurchase ?? 0,
  dpurchasedate: toDate(formState.dpurchasedate),
  ddeP_NAME: formState.ddeP_NAME ?? "",
  dphone: formState.dphone ?? "",
  dphonE2: formState.dphonE2 ?? "",
  dvaluedate: toDate(formState.dvaluedate),
  dvalue: formState.dvalue ?? 0,
  dcurrency: formState.dcurrency ?? "",
  dtelx: formState.dtelx ?? "",
  dpager: formState.dpager ?? "",
  ddate: toDate(formState.ddate),
  dlevel: formState.dlevel ?? 0,
  dsecondry: formState.dsecondry ?? false,
  remark: formState.remark ?? "",
  doldacccurr: formState.doldacccurr ?? 0,
  ddacccurr: formState.ddacccurr ?? 0,
  dcacccurr: formState.dcacccurr ?? 0,
  accumulatecode: formState.accumulatecode ?? "",
  och_rate: formState.och_rate ?? 0,
  scur: formState.scur ?? 0,
  dstop: formState.dstop ?? false,
  email: formState.email ?? "",
  mor1: formState.mor1 ?? "",
  mor2: formState.mor2 ?? "",
  mor3: formState.mor3 ?? "",
  mor4: formState.mor4 ?? "",
  mor5: formState.mor5 ?? "",
  acc_Rem: formState.acc_Rem ?? "",
  accshow_Rem: formState.accshow_Rem ?? false,
  dStop_Rem: formState.dStop_Rem ?? "",
  u_date_a: toDate(formState.u_date_a),
  u_time_a: toDate(formState.u_time_a),
  dperiod_allow: formState.dperiod_allow ?? 0,
  acC_TYPE: formState.acC_TYPE ?? 0,
  dtelother: formState.dtelother ?? "",
  demployee: formState.demployee ?? "",
  dslaes: formState.dslaes ?? "",
  emaiL_MSG: formState.emaiL_MSG ?? false,
  costCRelate: formState.costCRelate ?? false,
  fixExclusion: formState.fixExclusion ?? false,
  fixExclDate: toDate(formState.fixExclDate),
  accVatNo: formState.accVatNo ?? "",
  monDedction: formState.monDedction ?? 0,
  iqamaNo: formState.iqamaNo ?? "",
  iqamaExp: toDate(formState.iqamaExp),
  monDedStart: toDate(formState.monDedStart),
  nextDedDate: toDate(formState.nextDedDate),
  dedInterval: formState.dedInterval ?? 0,
  dbAccBfPr: formState.dbAccBfPr ?? 0,
  dcAccBfPr: formState.dcAccBfPr ?? 0,
  dOldAcc1Pr: formState.dOldAcc1Pr ?? 0,
  dOldAcc2Pr: formState.dOldAcc2Pr ?? 0,
  dOldAccPr: formState.dOldAccPr ?? 0,
  dbAccDurPr: formState.dbAccDurPr ?? 0,
  dcAccDurPr: formState.dcAccDurPr ?? 0,
  currDbBlnc: formState.currDbBlnc ?? 0,
  currCrBlnc: formState.currCrBlnc ?? 0,
  currNetBlnc: formState.currNetBlnc ?? 0,
  depAmount: formState.depAmount ?? 0,
  accumulateBalance: formState.accumulateBalance ?? 0,
  accumulateName: formState.accumulateName ?? "",
  dadd: formState.dadd ?? 0,
  dadD_Dep: formState.dadD_Dep ?? 0,
  dailyDep: formState.dailyDep ?? 0,
  ddeP_years: formState.ddeP_years ?? 0,
  depbal: formState.depbal ?? 0,
  depByTime: formState.depByTime ?? 0,
  depDayes: formState.depDayes ?? 0,
  dold: formState.dold ?? 0,
  dRem: formState.dRem ?? 0,
  dRem_Dep: formState.dRem_Dep ?? 0,
  endDate: toDate(formState.endDate),
  finalBAL: formState.finalBAL ?? 0,
  absCurrBlnce: formState.absCurrBlnce ?? 0,
  baL1: formState.baL1 ?? 0,
  baL2: formState.baL2 ?? 0,
  currNetBalance: formState.currNetBalance ?? 0,
  disp: formState.disp ?? "",
  ilCase: formState.ilCase ?? "",
  rColor: formState.rColor ?? 0,
  stB_BACK: formState.stB_BACK ?? "",
  oriFTYPE: formState.oriFTYPE ?? "",
  ftype: formState.ftype ?? "",
  docTypeName: formState.docTypeName ?? "",
  codE2: formState.codE2 ?? "",
  gRegNo: formState.gRegNo ?? 0,
  onumber: formState.onumber ?? 0,
  bookno: formState.bookno ?? "",
  fdate: toDate(formState.fdate),
  fcode: formState.fcode ?? "",
  tcode: formState.tcode ?? "",
  fname: formState.fname ?? "",
  tname: formState.tname ?? "",
  amount: formState.amount ?? 0,
  paid: formState.paid ?? 0,
  bamount: formState.bamount ?? 0,
  change: formState.change ?? 0,
  totdiscount: formState.totdiscount ?? 0,
  cost: formState.cost ?? 0,
  paide: formState.paide ?? 0,
  posted: formState.posted ?? 0,
  cH_RATE: formState.cH_RATE ?? 0,
  dutY_DAY: formState.dutY_DAY ?? 0,
  useR_NO: formState.useR_NO ?? 0,
  username: formState.username ?? "",
  seller: formState.seller ?? "",
  sellername: formState.sellername ?? "",
  ref: formState.ref ?? "",
  chK_NO: formState.chK_NO ?? "",
  chK_DATE: toDate(formState.chK_DATE),
  banK_NAME: formState.banK_NAME ?? "",
  name: formState.name ?? "",
  cost_Center: formState.cost_Center ?? "",
  jobNo: formState.jobNo ?? 0,
  orderNo: formState.orderNo ?? 0,
  dlvType: formState.dlvType ?? 0,
  paymode: formState.paymode ?? "",
  paymodeno: formState.paymodeno ?? "",
  taxcost: formState.taxcost ?? 0,
  shipcost: formState.shipcost ?? 0,
  othercost: formState.othercost ?? 0,
  custAddr: formState.custAddr ?? "",
  custTel: formState.custTel ?? "",
  custFax: formState.custFax ?? "",
  invoice_Date: toDate(formState.invoice_Date),
  u_DATE_E: toDate(formState.u_DATE_E),
  estUserNo: formState.estUserNo ?? "",
  estUserName: formState.estUserName ?? "",
  u_TIME_E: toDate(formState.u_TIME_E),
  invoicE_NO: formState.invoicE_NO ?? "",
  ncust: formState.ncust ?? "",
  codE3: formState.codE3 ?? "",
  nameref1: formState.nameref1 ?? "",
  cash_no: formState.cash_no ?? "",
  unitf: formState.unitf ?? 0,
  shifT_NO: formState.shifT_NO ?? "",
  nameref2: formState.nameref2 ?? "",
  brnno: formState.brnno ?? "",
  wsname: formState.wsname ?? "",
  wsno: formState.wsno ?? "",
  bwo: formState.bwo ?? 0,
  amount2: formState.amount2 ?? 0,
  ch_rate2: formState.ch_rate2 ?? 0,
  fileno: formState.fileno ?? 0,
  cmpacc: formState.cmpacc ?? 0,
  pantname: formState.pantname ?? "",
  remark1: formState.remark1 ?? "",
  remark2: formState.remark2 ?? "",
  diq: formState.diq ?? "",
  phrdis: formState.phrdis ?? 0,
  inuacc: formState.inuacc ?? "",
  amount3: formState.amount3 ?? 0,
  currName: formState.currName ?? "",
  fixExcName: formState.fixExcName ?? "",
  landNo: formState.landNo ?? "",
  landName: formState.landName ?? "",
  restAccName: formState.restAccName ?? "",
  restAccNo: formState.restAccNo ?? "",
  vouArrangeNo: formState.vouArrangeNo ?? "",
  vouDiscType: formState.vouDiscType ?? 0,
  vouDiscPer: formState.vouDiscPer ?? 0,
  vouDiscAmount: formState.vouDiscAmount ?? 0,
  vouTotDisc: formState.vouTotDisc ?? 0,
  itmTotDisc: formState.itmTotDisc ?? 0,
  itmTotQnt: formState.itmTotQnt ?? 0,
  invCost: formState.invCost ?? 0,
  totAmntWithoutDisc: formState.totAmntWithoutDisc ?? 0,
  totAmntBfDisc: formState.totAmntBfDisc ?? 0,
  totAmntAfItmDisc: formState.totAmntAfItmDisc ?? 0,
  vatAmnt: formState.vatAmnt ?? 0,
  totAmntAfVat: formState.totAmntAfVat ?? 0,
  selleR2: formState.selleR2 ?? "",
  sellernamE2: formState.sellernamE2 ?? "",
  cust2Accno: formState.cust2Accno ?? "",
  cust2Name: formState.cust2Name ?? "",
  cust2Mobile: formState.cust2Mobile ?? "",
  cust2Address: formState.cust2Address ?? "",
  invCode2: formState.invCode2 ?? "",
  gNot01: formState.gNot01 ?? "",
  gNot02: formState.gNot02 ?? "",
  gNot03: formState.gNot03 ?? "",
  gNot04: formState.gNot04 ?? "",
  gNot05: formState.gNot05 ?? "",
  gNot06: formState.gNot06 ?? "",
  gNot07: formState.gNot07 ?? "",
  gNot08: formState.gNot08 ?? "",
  gNot09: formState.gNot09 ?? "",
  gNot10: formState.gNot10 ?? "",
  gNot11: formState.gNot11 ?? "",
  gNot12: formState.gNot12 ?? "",
  gNot13: formState.gNot13 ?? "",
  gNot14: formState.gNot14 ?? "",
  gNot15: formState.gNot15 ?? "",
  maturityStart: toDate(formState.maturityStart),
  maturityEnd: toDate(formState.maturityEnd),
  rowBColor: formState.rowBColor ?? 0,
  acc_arrang: formState.acc_arrang ?? 0,
  accGranted: formState.accGranted ?? false,
  dNum: formState.dNum ?? 0,
  crNo: formState.crNo ?? "",
  cntryName: formState.cntryName ?? "",
  cntryIdCode: formState.cntryIdCode ?? "",
  cntrySubentity: formState.cntrySubentity ?? "",
  postalCode: formState.postalCode ?? "",
  cityName: formState.cityName ?? "",
  citySubDivsion: formState.citySubDivsion ?? "",
  plotId: formState.plotId ?? "",
  buildNo: formState.buildNo ?? "",
  streetname: formState.streetname ?? "",
  addStreetname: formState.addStreetname ?? "",
  g_Date01: toDate(formState.g_Date01),
  g_Date02: toDate(formState.g_Date02),
  ctActive: formState.ctActive ?? 0,
  curUntStr: formState.curUntStr ?? "",
  curUntNo: formState.curUntNo ?? 0,
  curAkrName: formState.curAkrName ?? "",
  curAkrNo: formState.curAkrNo ?? "",
});

// دالة معالجة القيم قبل الإرسال
// export const processFormData = (data) => {
//   const formatDate = (val) =>
//     val ? new Date(val).toISOString().split("T")[0] : null;

//   const processed = {};

//   for (const key in data) {
//     const value = data[key];

//     if (
//       key.toLowerCase().includes("date") ||
//       key.toLowerCase().includes("time")
//     ) {
//       processed[key] = value ? formatDate(value) : null;
//     } else if (typeof value === "string") {
//       processed[key] = value ?? "";
//     } else if (typeof value === "number") {
//       processed[key] = isNaN(value) ? 0 : value;
//     } else if (typeof value === "boolean") {
//       processed[key] = value;
//     } else if (value === null || value === undefined) {
//       processed[key] = "";
//     } else {
//       processed[key] = value;
//     }
//   }

//   return processed;
// };

// export const initialFormState =  {
//     dcodE1: "",
//     dcodE2: "",
//     dname: "",
//     dnamE2: "",
//     num: null,
//     doldacC1: 0,
//     doldacC2: 0,
//     doldacc: 0,
//     dcurrenT1: null,
//     dcurrenT2: null,
//     dcacc: 0,
//     ddacc: 0,
//     dcaccm: 0,
//     ddaccm: 0,
//     ddeP_AMOUNT: 0,
//     ddeP_PER: 0,
//     dacC_TYPE0: "",
//     dacC_TYPE: "",
//     dacC_TYPE2: "",
//     ddeP_CODE: null,
//     dfdate: "",
//     dtdate: null,
//     dacC_TNAME: null,
//     daddress: "",
//     daddresS2: "",
//     dcrediT_LIMT: 0,
//     dpurchase: 0,
//     dpurchasedate: "",
//     ddeP_NAME: "",
//     dphone: "",
//     dphonE2: "",
//     dvaluedate: "",
//     dvalue: 0,
//     dcurrency: "",
//     dtelx: "",
//     dpager: "",
//     ddate: "",
//     dlevel: 0,
//     dsecondry: false,
//     remark: "",
//     doldacccurr: 0,
//     ddacccurr: 0,
//     dcacccurr: 0,
//     accumulatecode: "",
//     och_rate: 0,
//     scur: 0,
//     dstop: false,
//     email: "",
//     mor1: "",
//     mor2: "",
//     mor3: "",
//     mor4: "",
//     mor5: "",
//     acc_Rem: "",
//     accshow_Rem: false,
//     dStop_Rem: "",
//     u_date_a: null,
//     u_time_a: null,
//     dperiod_allow: 0,
//     acC_TYPE: 0,
//     dtelother: "",
//     demployee: "",
//     dslaes: "",
//     emaiL_MSG: false,
//     costCRelate: false,
//     fixExclusion: false,
//     fixExclDate: null,
//     accVatNo: "",
//     monDedction: 0,
//     iqamaNo: "",
//     iqamaExp: null,
//     monDedStart: null,
//     nextDedDate: null,
//     dedInterval: 0,
//     dbAccBfPr: 0,
//     dcAccBfPr: 0,
//     dOldAcc1Pr: 0,
//     dOldAcc2Pr: 0,
//     dOldAccPr: 0,
//     dbAccDurPr: 0,
//     dcAccDurPr: 0,
//     currDbBlnc: 0,
//     currCrBlnc: 0,
//     currNetBlnc: 0,
//     depAmount: 0,
//     accumulateBalance: 0,
//     accumulateName: "",
//     dadd: 0,
//     dadD_Dep: 0,
//     dailyDep: 0,
//     ddeP_years: 0,
//     depbal: 0,
//     depByTime: 0,
//     depDayes: 0,
//     dold: 0,
//     dRem: 0,
//     dRem_Dep: 0,
//     endDate: null,
//     finalBAL: 0,
//     absCurrBlnce: 0,
//     baL1: 0,
//     baL2: 0,
//     currNetBalance: 0,
//     disp: "",
//     ilCase: "",
//     rColor: 0,
//     stB_BACK: "",
//     oriFTYPE: "",
//     ftype: "",
//     docTypeName: "",
//     codE2: "",
//     gRegNo: 0,
//     onumber: 0,
//     bookno: "",
//     fdate: null,
//     fcode: "",
//     tcode: "",
//     fname: "",
//     tname: "",
//     amount: 0,
//     paid: 0,
//     bamount: 0,
//     change: 0,
//     totdiscount: 0,
//     cost: 0,
//     paide: 0,
//     posted: 0,
//     cH_RATE: 0,
//     dutY_DAY: 0,
//     useR_NO: 0,
//     username: "",
//     seller: "",
//     sellername: "",
//     ref: "",
//     chK_NO: "",
//     chK_DATE: null,
//     banK_NAME: "",
//     name: "",
//     cost_Center: "",
//     jobNo: 0,
//     orderNo: 0,
//     dlvType: 0,
//     paymode: "",
//     paymodeno: "",
//     taxcost: 0,
//     shipcost: 0,
//     othercost: 0,
//     custAddr: "",
//     custTel: "",
//     custFax: "",
//     invoice_Date: null,
//     u_DATE_E: null,
//     estUserNo: "",
//     estUserName: "",
//     u_TIME_E: null,
//     invoicE_NO: "",
//     ncust: "",
//     codE3: "",
//     nameref1: "",
//     cash_no: "",
//     unitf: 0,
//     shifT_NO: "",
//     nameref2: "",
//     brnno: "",
//     wsname: "",
//     wsno: "",
//     bwo: 0,
//     amount2: 0,
//     ch_rate2: 0,
//     fileno: 0,
//     cmpacc: 0,
//     pantname: "",
//     remark1: "",
//     remark2: "",
//     diq: "",
//     phrdis: 0,
//     inuacc: "",
//     amount3: 0,
//     currName: "",
//     fixExcName: "",
//     landNo: "",
//     landName: "",
//     restAccName: "",
//     restAccNo: "",
//     vouArrangeNo: "",
//     vouDiscType: 0,
//     vouDiscPer: 0,
//     vouDiscAmount: 0,
//     vouTotDisc: 0,
//     itmTotDisc: 0,
//     itmTotQnt: 0,
//     invCost: 0,
//     totAmntWithoutDisc: 0,
//     totAmntBfDisc: 0,
//     totAmntAfItmDisc: 0,
//     vatAmnt: 0,
//     totAmntAfVat: 0,
//     selleR2: "",
//     sellernamE2: "",
//     cust2Accno: "",
//     cust2Name: "",
//     cust2Mobile: "",
//     cust2Address: "",
//     invCode2: "",
//     gNot01: "",
//     gNot02: "",
//     gNot03: "",
//     gNot04: "",
//     gNot05: "",
//     gNot06: "",
//     gNot07: "",
//     gNot08: "",
//     gNot09: "",
//     gNot10: "",
//     gNot11: "",
//     gNot12: "",
//     gNot13: "",
//     gNot14: "",
//     gNot15: "",
//     maturityStart: null,
//     maturityEnd: null,
//     rowBColor: 0,
//     acc_arrang: 0,
//     accGranted: false,
//     dNum: 0,
//     crNo: "",
//     cntryName: "",
//     cntryIdCode: "",
//     cntrySubentity: "",
//     postalCode: "",
//     cityName: "",
//     citySubDivsion: "",
//     plotId: "",
//     buildNo: "",
//     streetname: "",
//     addStreetname: "",
//     g_Date01: null,
//     g_Date02: null,
//     ctActive: 0,
//     curUntStr: "",
//     curUntNo: 0,
//     curAkrName: "",
//     curAkrNo: "",
//   };
