export const initialFormState = {
  dcodE1: "",
  dcodE2: "",
  dname: "",
  dnamE2: "",
  num: 0,
  doldacC1: 0,
  doldacC2: 0,
  doldacc: 0,
  dcurrenT1: 0,
  dcurrenT2: 0,
  dcacc: 0,
  ddacc: 0,
  dcaccm: 0,
  ddaccm: 0,
  ddeP_AMOUNT: 0,
  ddeP_PER: 0,
  dacC_TYPE0: "",
  dacC_TYPE: "",
  dacC_TYPE2: "",
  ddeP_CODE: "",
  dfdate: null,
  dtdate: null,
  dacC_TNAME: "",
  daddress: "",
  daddresS2: "",
  dcrediT_LIMT: 0,
  dpurchase: 0,
  dpurchasedate: null,
  ddeP_NAME: "",
  dphone: "",
  dphonE2: "",
  dvaluedate: null,
  dvalue: 0,
  dcurrency: "",
  dtelx: "",
  dpager: "",
  ddate: null,
  dlevel: 0,
  dsecondry: false,
  dsave: 0,
  group: "",
  jV_NO: "",
  jV_AMOUNT: 0,
  jV_DATE: null,
  paY_NO: "",
  paY_AMOUNT: 0,
  paY_DATE: null,
  rcV_NO: "",
  rcV_AMOUNT: 0,
  rcV_DATE: null,
  saL_C_NO: "",
  saL_C_AMOUNT: 0,
  saL_C_DATE: null,
  saL_CR_NO: "",
  saL_CR_AMOUNT: 0,
  saL_CR_DATE: null,
  saL_R_C_NO: "",
  saL_R_C_AMOUNT: 0,
  saL_R_C_DATE: null,
  saL_R_CR_NO: "",
  saL_R_CR_DATE: null,
  saL_R_CR_AMOUNT: 0,
  puR_C_NO: "",
  puR_C_AMOUNT: 0,
  puR_C_DATE: null,
  puR_CR_NO: "",
  puR_CR_AMOUNT: 0,
  puR_CR_DATE: null,
  puR_R_C_NO: "",
  puR_R_C_AMOUNT: 0,
  puR_R_C_DATE: null,
  puR_R_CR_NO: "",
  puR_R_CR_DATE: null,
  puR_R_CR_AMOUNT: 0,
  costCenter: "",
  wsH_NAME: "",
  wsH_CODE: "",
  acceng: "",
  crbnk: "",
  crcod: "",
  ordnum: "",
  orddate: null,
  ordbnk: "",
  dutdate: null,
  vername: "",
  amount: 0,
  paidcon: "",
  remark: "",
  trnfrm: "",
  trnto: "",
  rcvcon: "",
  trnpar: "",
  cryshp: "",
  lmdtrn: null,
  lmdrsv: null,
  doldacccurr: 0,
  ddacccurr: 0,
  dcacccurr: 0,
  rcolor: 0,
  ordnun: "",
  accumulatecode: "",
  och_rate: 0,
  dstop: false,
  email: "",
  mor1: "",
  mor2: "",
  mor3: "",
  mor4: "",
  mor5: "",
  acc_Rem: "",
  accshow_Rem: false,
  dStop_Rem: "",
  ldate_debit: null,
  ldate_credit: null,
  chk_tdate: null,
  chK_DYES: 0,
  chk_dayes: 0,
  scur: 0,
  oldcode: "",
  whs_code: "",
  u_date_a: null,
  u_time_a: null,
  dperiod_allow: 0,
  acC_TYPE: 0,
  dtelother: "",
  demployee: "",
  dslaes: "",
  emaiL_MSG: false,
  dNum: 0,
  es_Date: null,
  userNo: "",
  edDate: null,
  userName: "",
  eUserNo: "",
  eUserName: "",
};

const toDate = (val) => {
  if (!val) return null;
  try {
    return new Date(val).toISOString();
  } catch {
    return null;
  }
};

export const processFormData = (formState) => ({
  dcodE1: formState.dcodE1 ?? "",
  dcodE2: formState.dcodE2 ?? "",
  dname: formState.dname ?? "",
  dnamE2: formState.dnamE2 ?? "",
  num: formState.num ?? 0,
  doldacC1: formState.doldacC1 ?? 0,
  doldacC2: formState.doldacC2 ?? 0,
  doldacc: formState.doldacc ?? 0,
  dcurrenT1: formState.dcurrenT1 ?? 0,
  dcurrenT2: formState.dcurrenT2 ?? 0,
  dcacc: formState.dcacc ?? 0,
  ddacc: formState.ddacc ?? 0,
  dcaccm: formState.dcaccm ?? 0,
  ddaccm: formState.ddaccm ?? 0,
  ddeP_AMOUNT: formState.ddeP_AMOUNT ?? 0,
  ddeP_PER: formState.ddeP_PER ?? 0,
  dacC_TYPE0: formState.dacC_TYPE0 != null ? String(formState.dacC_TYPE0) : "",
  dacC_TYPE: formState.dacC_TYPE != null ? String(formState.dacC_TYPE) : "",
  dacC_TYPE2: formState.dacC_TYPE2 != null ? String(formState.dacC_TYPE2) : "",
  ddeP_CODE: formState.ddeP_CODE ?? "",
  dfdate: toDate(formState.dfdate),
  dtdate: toDate(formState.dtdate),
  dacC_TNAME: formState.dacC_TNAME ?? "",
  daddress: formState.daddress ?? "",
  daddresS2: formState.daddresS2 ?? "",
  dcrediT_LIMT: formState.dcrediT_LIMT ?? 0,
  dpurchase: formState.dpurchase ?? 0,
  dpurchasedate: toDate(formState.dpurchasedate),
  ddeP_NAME: formState.ddeP_NAME ?? "",
  dphone: formState.dphone ?? "",
  dphonE2: formState.dphonE2 ?? "",
  dvaluedate: toDate(formState.dvaluedate),
  dvalue: formState.dvalue ?? 0,
  dcurrency: formState.dcurrency ?? "",
  dtelx: formState.dtelx ?? "",
  dpager: formState.dpager ?? "",
  ddate: toDate(formState.ddate),
  dlevel: formState.dlevel ?? 0,
  dsecondry: formState.dsecondry ?? false,
  dsave: formState.dsave ?? 0,
  group: formState.group ?? "",
  jV_NO: formState.jV_NO ?? "",
  jV_AMOUNT: formState.jV_AMOUNT ?? 0,
  jV_DATE: toDate(formState.jV_DATE),
  paY_NO: formState.paY_NO ?? "",
  paY_AMOUNT: formState.paY_AMOUNT ?? 0,
  paY_DATE: toDate(formState.paY_DATE),
  rcV_NO: formState.rcV_NO ?? "",
  rcV_AMOUNT: formState.rcV_AMOUNT ?? 0,
  rcV_DATE: toDate(formState.rcV_DATE),
  saL_C_NO: formState.saL_C_NO ?? "",
  saL_C_AMOUNT: formState.saL_C_AMOUNT ?? 0,
  saL_C_DATE: toDate(formState.saL_C_DATE),
  saL_CR_NO: formState.saL_CR_NO ?? "",
  saL_CR_AMOUNT: formState.saL_CR_AMOUNT ?? 0,
  saL_CR_DATE: toDate(formState.saL_CR_DATE),
  saL_R_C_NO: formState.saL_R_C_NO ?? "",
  saL_R_C_AMOUNT: formState.saL_R_C_AMOUNT ?? 0,
  saL_R_C_DATE: toDate(formState.saL_R_C_DATE),
  saL_R_CR_NO: formState.saL_R_CR_NO ?? "",
  saL_R_CR_DATE: toDate(formState.saL_R_CR_DATE),
  saL_R_CR_AMOUNT: formState.saL_R_CR_AMOUNT ?? 0,
  puR_C_NO: formState.puR_C_NO ?? "",
  puR_C_AMOUNT: formState.puR_C_AMOUNT ?? 0,
  puR_C_DATE: toDate(formState.puR_C_DATE),
  puR_CR_NO: formState.puR_CR_NO ?? "",
  puR_CR_AMOUNT: formState.puR_CR_AMOUNT ?? 0,
  puR_CR_DATE: toDate(formState.puR_CR_DATE),
  puR_R_C_NO: formState.puR_R_C_NO ?? "",
  puR_R_C_AMOUNT: formState.puR_R_C_AMOUNT ?? 0,
  puR_R_C_DATE: toDate(formState.puR_R_C_DATE),
  puR_R_CR_NO: formState.puR_R_CR_NO ?? "",
  puR_R_CR_DATE: toDate(formState.puR_R_CR_DATE),
  puR_R_CR_AMOUNT: formState.puR_R_CR_AMOUNT ?? 0,
  costCenter: formState.costCenter ?? "",
  wsH_NAME: formState.wsH_NAME ?? "",
  wsH_CODE: formState.wsH_CODE ?? "",
  acceng: formState.acceng ?? "",
  crbnk: formState.crbnk ?? "",
  crcod: formState.crcod ?? "",
  ordnum: formState.ordnum ?? "",
  orddate: toDate(formState.orddate),
  ordbnk: formState.ordbnk ?? "",
  dutdate: toDate(formState.dutdate),
  vername: formState.vername ?? "",
  amount: formState.amount ?? 0,
  paidcon: formState.paidcon ?? "",
  remark: formState.remark ?? "",
  trnfrm: formState.trnfrm ?? "",
  trnto: formState.trnto ?? "",
  rcvcon: formState.rcvcon ?? "",
  trnpar: formState.trnpar ?? "",
  cryshp: formState.cryshp ?? "",
  lmdtrn: toDate(formState.lmdtrn),
  lmdrsv: toDate(formState.lmdrsv),
  doldacccurr: formState.doldacccurr ?? 0,
  ddacccurr: formState.ddacccurr ?? 0,
  dcacccurr: formState.dcacccurr ?? 0,
  rcolor: formState.rcolor ?? 0,
  ordnun: formState.ordnun ?? "",
  accumulatecode: formState.accumulatecode ?? "",
  och_rate: formState.och_rate ?? 0,
  dstop: formState.dstop ?? false,
  email: formState.email ?? "",
  mor1: formState.mor1 ?? "",
  mor2: formState.mor2 ?? "",
  mor3: formState.mor3 ?? "",
  mor4: formState.mor4 ?? "",
  mor5: formState.mor5 ?? "",
  acc_Rem: formState.acc_Rem ?? "",
  accshow_Rem: formState.accshow_Rem ?? false,
  dStop_Rem: formState.dStop_Rem ?? "",
  ldate_debit: toDate(formState.ldate_debit),
  ldate_credit: toDate(formState.ldate_credit),
  chk_tdate: toDate(formState.chk_tdate),
  chK_DYES: formState.chK_DYES ?? 0,
  chk_dayes: formState.chk_dayes ?? 0,
  scur: formState.scur ?? 0,
  oldcode: formState.oldcode ?? "",
  whs_code: formState.whs_code ?? "",
  u_date_a: toDate(formState.u_date_a),
  u_time_a: toDate(formState.u_time_a),
  dperiod_allow: formState.dperiod_allow ?? 0,
  acC_TYPE: formState.acC_TYPE ?? 0,
  dtelother: formState.dtelother ?? "",
  demployee: formState.demployee ?? "",
  dslaes: formState.dslaes ?? "",
  emaiL_MSG: formState.emaiL_MSG ?? false,
  dNum: formState.dNum ?? 0,
  es_Date: toDate(formState.es_Date),
  userNo: formState.userNo ?? "",
  edDate: toDate(formState.edDate),
  userName: formState.userName ?? "",
  eUserNo: formState.eUserNo ?? "",
  eUserName: formState.eUserName ?? "",
});
